title = "alltests"

[properties]
path = ""
time = ""

[instances]
"Env.VisRangeInFog_0/Env.RainRate_50" = "Carmaker_test.0"
"Env.VisRangeInFog_50/Env.RainRate_50" = "Carmaker_test.1"
"Env.VisRangeInFog_50/Env.RainRate_0" = "Carmaker_test.2"
"Env.VisRangeInFog_50/Env.RainRate_100" = "Carmaker_test.3"